/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { InstallmentService } from "../installment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { InstallmentCreateInput } from "./InstallmentCreateInput";
import { Installment } from "./Installment";
import { InstallmentFindManyArgs } from "./InstallmentFindManyArgs";
import { InstallmentWhereUniqueInput } from "./InstallmentWhereUniqueInput";
import { InstallmentUpdateInput } from "./InstallmentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class InstallmentControllerBase {
  constructor(
    protected readonly service: InstallmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Installment })
  @nestAccessControl.UseRoles({
    resource: "Installment",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createInstallment(
    @common.Body() data: InstallmentCreateInput
  ): Promise<Installment> {
    return await this.service.createInstallment({
      data: data,
      select: {
        amount: true,
        createdAt: true,
        dueDate: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Installment] })
  @ApiNestedQuery(InstallmentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Installment",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async installments(@common.Req() request: Request): Promise<Installment[]> {
    const args = plainToClass(InstallmentFindManyArgs, request.query);
    return this.service.installments({
      ...args,
      select: {
        amount: true,
        createdAt: true,
        dueDate: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Installment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Installment",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async installment(
    @common.Param() params: InstallmentWhereUniqueInput
  ): Promise<Installment | null> {
    const result = await this.service.installment({
      where: params,
      select: {
        amount: true,
        createdAt: true,
        dueDate: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Installment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Installment",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateInstallment(
    @common.Param() params: InstallmentWhereUniqueInput,
    @common.Body() data: InstallmentUpdateInput
  ): Promise<Installment | null> {
    try {
      return await this.service.updateInstallment({
        where: params,
        data: data,
        select: {
          amount: true,
          createdAt: true,
          dueDate: true,
          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Installment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Installment",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteInstallment(
    @common.Param() params: InstallmentWhereUniqueInput
  ): Promise<Installment | null> {
    try {
      return await this.service.deleteInstallment({
        where: params,
        select: {
          amount: true,
          createdAt: true,
          dueDate: true,
          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
